name: flutter_injected_web3
description: A web3 injection library for flutter.
version: 1.0.1
homepage: https://github.com/Orange-Wallet/flutter_injected_web3

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.0.0"


dependencies:
  flutter_inappwebview: 6.0.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

flutter:
  uses-material-design: true
  assets:
    - packages/flutter_injected_web3/assets/provider.min.js
